server:
  port: 3344

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: git@github.com:shaoshaossm/springcloud-config.git
          search-paths:
            - springcloud-config
      label: main
    #    切记这个一定要开，要不然报405
    bus:
      refresh:
        enabled: true

  rabbitmq:
    host: 192.168.174.131
    port: 5672
    username: admin
    password: hxl158120
#暴露端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'


